### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by oyeanuj** [lumenlearning/react-accordionlly#1]
Hi @monkecheese ! I was very curious about your plugin and would love to see a demo example of how it works. I imagine that would help a lot of people when making their choices.

**Comment by monkecheese** [comment]
Great suggestion, thank you!  I've been tied up with other projects and haven't had really had much time to put a polished demo together.  However, I have included a basic demo folder to the project that you can get working on your machine.

1. Start by cloning the project and `cd` into it.  
2. Next, `npm install` and wait while it installs all of its dependencies.
3. Finally, run `webpack-dev-server --content-base ./`.  This should load a development server on port 8080 at the root of the project.  Just navigate to `localhost:8080/demo/` in your browser and you should see an unstyled page with four "cases" demonstrating the different prop values you can pass in.

I hope that's helpful.  If you run into any issues or have additional feedback, feel free to let me know  :)

**Comment by monkecheese** [comment]
The above steps have been added to README file for getting a demo running in a local environment.  This should resolve the issue until I get a chance to build a proper live demo page for it.  Cheers!
